spring:
  application:
    name: weidun-admin
  profiles:
    active: dev # 默认开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

mybatis:
  mapper-locations:
    - classpath:org/jiang/admin/dao/*.xml
    - classpath*:org/jiang/mapper/*.xml

redis:
  database: weidun
  key:
    admin: 'uwd:admin'
    resourceList: 'uwd:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: # 安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /user/login
      - /user/register
      - /user/info
      - /user/logout
      - /minio/upload

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: weidun-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    accessKeyId: LTAI4Fyozv7v34gpttovBvPV
    accessKeySecret: 8uKHiJvWi5W0hrpEUQfe1MMTDlvohN
    bucketName: wei-dun
    policy:
      expire: 300 # 签名有效期(s)
    maxSize: 10 # 上传文件大小(m)
    callback: http
    dir:
      prefix: weidun/images/ # 文件上传路径前缀
