spring:
  application:
    name: weidun-admin
  profiles:
    active: dev # 默认开发环境


secure:
  ignored:
    urls: # 安全路径白名单
      - /swagger-ui.html

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: weidun-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
